baseurl: "" # The subpath of your site. Use "" if you're hosting a blog at the root level.
url: "https://www.jaetech.org" # the base hostname & protocol for your site.
title: "James Edwards' blog"


paginate: 3 #articles per page
paginate_path: /blog/page:num #makes pagination working


#contacts
git: "https://github.com/jae2"  #Add your github url here.
twitter: "https://twitter.com/jam_ez_"  #Add your twitter url here.
rss: "https://www.jaetech.org/feed.xml"  #Add your twitter url here.
stackoverflow: ""

gems:
  - jekyll-sitemap

# This is used by feed.xml. Uncomment if you want to use it.
description: "blogging about infra stuff"

exclude:
  - "README.md"
  - "CHANGELOG.md"
  - "Gemfile"
  - "Gemfile.lock"
permalink: :title
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

mini_magick:
    small:
        source: images/
        destination: images/small/
        resize: "200x200"
    medium:
        source: images/
        destination: images/medium/
        resize: "640x480"
